Unit tests
fredmnpinto/PageGuild pull request #19
Opened 2022-01-13 19:27 UTC by 21F0rc3

2022-01-13 23:56 UTC, fredmnpinto requested changes

2022-01-13 23:56 UTC, fredmnpinto commented on tests/Unit/AddressControllerTest.php
> +        AddressController::desactivateAddress($address->id);
Em ingles, desativar é deactivate

2022-01-13 23:56 UTC, fredmnpinto commented on tests/Unit/AddressControllerTest.php
> +        $response = $this->actingAs($user)
devemos checar ao menos se ha algum erro na session

2022-01-13 23:56 UTC, fredmnpinto commented on tests/Unit/AddressControllerTest.php
> +        $this->assertNotNull($newAddress, "O endereço não foi criado. Ha um problema com a AddressController::createAddress()");
checa tambem se o newAddress é igual aos parametros que vc criou

2022-01-13 23:56 UTC, fredmnpinto commented on tests/Unit/BookControllerTest.php
> +        $book_id = Book::first()->item_id;
testa criar um livro novo e adicionar a ele um autor

2022-01-13 23:56 UTC, fredmnpinto commented on tests/Unit/BookControllerTest.php
> +        $book_id = Book::first()->item_id;
a mesma coisa, criar um livro novo e associar o genero

2022-01-14 00:22 UTC, 21F0rc3 commented on tests/Unit/AddressControllerTest.php
> +        AddressController::desactivateAddress($address->id);
Feito

2022-01-14 00:26 UTC, 21F0rc3 commented on tests/Unit/AddressControllerTest.php
> +        $this->assertNotNull($newAddress, "O endereço não foi criado. Ha um problema com a AddressController::createAddress()");
feito

2022-01-14 00:28 UTC, 21F0rc3 commented on tests/Unit/BookControllerTest.php
> +        $book_id = Book::first()->item_id;
mas esta função so testa se ela vai buscar autores, não inserir. Não acho boa ideia testar duas coisas diferentes no mesmo

2022-01-14 00:28 UTC, 21F0rc3 commented on tests/Unit/AddressControllerTest.php
> +        $response = $this->actingAs($user)
não entendi o que e para fazer

2022-01-14 01:19 UTC, merged